name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: gadget-inc/puppeteer-action@master
        with:
          args: yarn
      - name: Lint
        uses: gadget-inc/puppeteer-action@master
        with:
          args: yarn lint
      - name: Test
        uses: gadget-inc/puppeteer-action@master
        with:
          args: yarn test
